// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuintaEntrega.Context;

#nullable disable

namespace QuintaEntrega.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240109030810_ultimamigration3")]
    partial class ultimamigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QuintaEntrega.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Destino");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Cidade = "Ipojuca",
                            Estado = "Pernambuco",
                            Img = "https://www.cvc.com.br/dicas-de-viagem/wp-content/uploads/2023/05/maragogi-porto-de-galinhas-vista-1170x650.jpg",
                            Nome = "Porto de Galinhas",
                            Pais = "Brasil",
                            Valor = "R$1500,00"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Santo Antônio de Jesus",
                            Estado = "Bahia",
                            Img = "https://www.bahianoticias.com.br/_next/image?url=https%3A%2F%2Fwww.bahianoticias.com.br%2Ffotos%2Fhall_travellings%2F228%2FIMAGEM_TRAVELLING_9.jpg%3Fchecksum%3D1674165596&w=1920&q=75",
                            Nome = "Balonismo",
                            Pais = "Brasil",
                            Valor = "R$2500,00"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Arraial do Cabo",
                            Estado = "Rio de Janeiro",
                            Img = "https://www.melhoresdestinos.com.br/wp-content/uploads/2020/09/arraial-do-cabo-capa2019-1536x805.jpg",
                            Nome = "Arraial do Cabo",
                            Pais = "Brasil",
                            Valor = "R$5500,00"
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Gramado",
                            Estado = "Rio Grande do Sul",
                            Img = "https://magazine.zarpo.com.br/wp-content/uploads/2019/05/gramado-tudo-sobre-a-cidade-mais-charmosa-do-rio-grande-do-sul-770x500.jpg",
                            Nome = "Natal Luz",
                            Pais = "Brasil",
                            Valor = "R$5000,00"
                        },
                        new
                        {
                            Id = 7,
                            Cidade = "Paris",
                            Estado = "-",
                            Img = "https://www.cp4.com.br/wp-content/uploads/2019/02/Paris.jpg",
                            Nome = "Torre Eiffel",
                            Pais = "França",
                            Valor = "R$8500,00"
                        },
                        new
                        {
                            Id = 8,
                            Cidade = "Cancun",
                            Estado = "Cidade do México",
                            Img = "https://www.remessaonline.com.br/blog/wp-content/uploads/2022/05/viagem-para-cancun-1170x780.jpg.optimal.jpg",
                            Nome = "Cancun",
                            Pais = "México",
                            Valor = "R$9500,00"
                        },
                        new
                        {
                            Id = 9,
                            Cidade = "Atenas",
                            Estado = "Grécia",
                            Img = "https://www.costacruzeiros.com/content/dam/costa/costa-magazine/articles-magazine/travel/greece-travel/grecia_d.jpg.image.648.487.high.jpg",
                            Nome = "Grécia",
                            Pais = "Grécia",
                            Valor = "R$13500,00"
                        },
                        new
                        {
                            Id = 10,
                            Cidade = "Sidney",
                            Estado = "-",
                            Img = "https://www.estudarfora.org.br/wp-content/uploads/2021/01/Australia.jpg.webp",
                            Nome = "Austrália",
                            Pais = "Austrália",
                            Valor = "R$9500,00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
